name: Generate snake animation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          palette: github-dark

      - name: Make sure dist exists
        run: mkdir -p dist

      - name: Move snake.svg to dist
        run: mv snake.svg dist/snake.svg

      - name: Push snake.svg to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          directory: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
